# Generated by Django 5.2.6 on 2025-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funds_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated to the project', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
    ]
